"""
scripts/setup_workbook.py

One-time workbook setup script.
Run this once per workbook to:
  1. Build Dashboard 2 with live CA stats
  2. Inject the AppTools VBA module
  3. Save the workbook

Usage:
    python3 setup_workbook.py "/path/to/workbook.xlsm"

Or hardcode the path below and just run:
    python3 setup_workbook.py
"""

import sys
import os

# ── Config ────────────────────────────────────────────────────
# Hardcode your workbook path here so you can just double-click/run
DEFAULT_WORKBOOK = (
    "/Users/bryan/Library/CloudStorage/"
    "OneDrive-tcsny.net/PSO/Projects/Connell Foley/Customer Data/"
    "Connell Foley ZP DGW_rev101525.xlsm"
)

# Path to app-tools repo (adjust if different)
APP_TOOLS_PATH = os.path.expanduser("~/AppTools/app-tools")
if not os.path.exists(APP_TOOLS_PATH):
    # Fallback to dev location
    APP_TOOLS_PATH = os.path.expanduser(
        "~/Documents/GitHub/app-tools")

sys.path.insert(0, APP_TOOLS_PATH)

# ── VBA module code ───────────────────────────────────────────
VBA_MODULE_NAME = "AppTools"
VBA_CODE = """\
' ============================================================
' App Tools — VBA Module
' Auto-generated by setup_workbook.py
' DO NOT EDIT — re-run setup_workbook.py to regenerate
'
' Repo: https://github.com/qpx7mxr9/app-tools
' ============================================================

' ── CA Tools Dashboard ────────────────────────────────────────
Sub Dashboard_Build()
    RunPython "import sys, os; sys.path.insert(0, os.path.expanduser('~/AppTools/app-tools')); import dashboard; dashboard.build_dashboard()"
End Sub

Sub Dashboard_Refresh()
    RunPython "import sys, os; sys.path.insert(0, os.path.expanduser('~/AppTools/app-tools')); import dashboard; dashboard.refresh_ca_block()"
End Sub

' ── Common Areas ─────────────────────────────────────────────
Sub ZCA_RunReconciliation()
    RunPython "import sys, os; sys.path.insert(0, os.path.expanduser('~/AppTools/app-tools')); import zca_recon; zca_recon.run_reconciliation()"
End Sub

Sub ZCA_ExportUpdate()
    RunPython "import sys, os; sys.path.insert(0, os.path.expanduser('~/AppTools/app-tools')); import zca_recon; zca_recon.export_update()"
End Sub

Sub ZCA_ExportAdd()
    RunPython "import sys, os; sys.path.insert(0, os.path.expanduser('~/AppTools/app-tools')); import zca_recon; zca_recon.export_add()"
End Sub

' ── Add stubs for new tools below ────────────────────────────
"""


# ── Main ──────────────────────────────────────────────────────

def main():
    wb_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_WORKBOOK
    wb_path = os.path.expanduser(wb_path)

    if not os.path.exists(wb_path):
        print(f"ERROR: Workbook not found:\n  {wb_path}")
        sys.exit(1)

    print(f"Setting up workbook:")
    print(f"  {wb_path}")
    print()

    import xlwings as xw

    print("Opening workbook...")
    app = xw.App(visible=True)
    wb  = app.books.open(wb_path)

    # ── Step 1: Build Dashboard 2 ─────────────────────────────
    print("Building Dashboard 2...")
    try:
        from dashboard.builder import _build
        _build(wb)
        print("  ✓ Dashboard 2 built")
    except Exception as e:
        import traceback
        print(f"  ✗ Dashboard build failed: {e}")
        traceback.print_exc()

    # ── Step 2: Inject VBA module ─────────────────────────────
    print("Injecting VBA module...")
    try:
        vb_project = wb.api.VBProject
        # Remove existing AppTools module if present
        for comp in list(vb_project.VBComponents):
            try:
                if comp.Name == VBA_MODULE_NAME:
                    vb_project.VBComponents.Remove(comp)
                    print(f"  Removed existing {VBA_MODULE_NAME} module")
            except Exception:
                pass
        # Add fresh module
        module = vb_project.VBComponents.Add(1)  # 1 = vbext_ct_StdModule
        module.Name = VBA_MODULE_NAME
        module.CodeModule.AddFromString(VBA_CODE)
        print(f"  ✓ VBA module '{VBA_MODULE_NAME}' injected")
    except Exception as e:
        print(f"  ✗ VBA injection failed: {e}")
        print()
        print("  To add VBA manually:")
        print("  1. Open VBA Editor (Alt+F11 or Tools > Macros > Edit)")
        print("  2. Insert > Module")
        print("  3. Import the file: app-tools/vba_stub.bas")
        _save_bas_file(wb_path)

    # ── Step 3: Save ──────────────────────────────────────────
    print("Saving workbook...")
    try:
        wb.save()
        print("  ✓ Saved")
    except Exception as e:
        print(f"  ✗ Save failed: {e}")
        print("  Try saving manually in Excel.")

    print()
    print("Setup complete. You can close this window.")
    print()
    try:
        input("Press Enter to close Excel and exit...")
    except EOFError:
        pass  # non-interactive run — leave Excel open for user to review
    try:
        wb.close(save_changes=False)
        app.quit()
    except Exception:
        pass


def _save_bas_file(wb_path):
    """Save VBA code as a .bas file next to the workbook for manual import."""
    bas_path = os.path.splitext(wb_path)[0] + "_AppTools.bas"
    with open(bas_path, "w") as f:
        f.write(VBA_CODE)
    print(f"  VBA saved to: {bas_path}")
    print("  Import it via VBA Editor > File > Import File")


if __name__ == "__main__":
    main()
